name: Update Episodes

# Controls when the workflow will run
on:
    workflow_dispatch:
    schedule:
      - cron: '0 0 * * *' # runs every day at 8

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
        contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.3.0
      - run: pip install -r requirements.txt
      - run: python python/crawl_new_episodes.py
        env:
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: action - update episodes from spotify
